checkmarx:
  version: 9.0
  username: XXXXXX
  password: XXXXXX
  client-id: XXXXXX
  client-secret: XXXXXX
  scope: sast_api access_control_api management_and_orchestration_api
  team: /CxServer/Checkmarx
  base-url: https://cx.local
  url: ${checkmarx.base-url}/cxrestapi
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
